#!/usr/bin/env bash
# Provision an Azure Machine Learning workspace and capture its MLflow URI.
#
# Prerequisites: Azure CLI installed and `az login` already completed.
# The script is idempotent: re-running it reuses existing resources.
set -euo pipefail

# ---- Configuration (override via environment variables if desired) ----------
RG="${RG:-rg-mlops-predmaint}"
WORKSPACE="${WORKSPACE:-mlw-predmaint}"
LOCATION="${LOCATION:-swedencentral}"  # subscription policy allows: swedencentral, germanywestcentral, switzerlandnorth

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env"

echo ">> Installing/updating the az ml extension..."
az extension add -n ml --upgrade --yes 1>/dev/null

echo ">> Registering required resource providers (first run only)..."
az provider register -n Microsoft.MachineLearningServices 1>/dev/null || true

echo ">> Creating resource group '${RG}' in '${LOCATION}'..."
az group create -n "${RG}" -l "${LOCATION}" 1>/dev/null

echo ">> Creating Azure ML workspace '${WORKSPACE}' (this can take a few minutes)..."
az ml workspace create -n "${WORKSPACE}" -g "${RG}" -l "${LOCATION}" 1>/dev/null

echo ">> Fetching the MLflow tracking URI..."
TRACKING_URI="$(az ml workspace show -n "${WORKSPACE}" -g "${RG}" \
  --query mlflow_tracking_uri -o tsv)"
SUBSCRIPTION_ID="$(az account show --query id -o tsv)"

cat > "${ENV_FILE}" <<EOF
# Auto-generated by azure/setup_workspace.sh
AZURE_ML_TRACKING_URI=${TRACKING_URI}
AZURE_SUBSCRIPTION_ID=${SUBSCRIPTION_ID}
AZURE_RESOURCE_GROUP=${RG}
AZURE_WORKSPACE=${WORKSPACE}
EXPERIMENT_NAME=predictive-maintenance
REGISTERED_MODEL_NAME=PredictiveMaintenanceModel
EOF

echo ">> Done. Wrote ${ENV_FILE}"
echo "   AZURE_ML_TRACKING_URI=${TRACKING_URI}"
